plugins { id 'java-library'; id 'maven-publish' }
dependencies {
    api project(':keycloak-auth-autoconfigure')
    api 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    api 'org.springframework.boot:spring-boot-starter-security'
    api 'org.springframework.boot:spring-boot-starter-actuator'
}
publishing { publications { maven(MavenPublication) { from components.java } } }