def telegram

pipeline {
    agent any
    stages {
        stage('Start') {
            steps {
                script {
                    telegram = load 'jenkins/telegram.groovy'
                    withBuildUser {
                        telegram.notifyStart(env.BUILD_USER)
                    }
                }
            }
        }

        stage('Build, Check, Publish To Maven Local') {
            steps {
                sh '''
                  chmod +x gradlew
                  ./gradlew clean test spotlessCheck publishToMavenLocal --no-daemon
                '''
            }
        }
    }

    post {
        success {
            script {
                telegram.deleteStartMessage()
                withBuildUser {
                    telegram.notifyFinish("✅ SUCCESS", env.BUILD_USER, currentBuild.duration)
                }
            }
        }
        failure {
            script {
                telegram.deleteStartMessage()
                withBuildUser {
                    telegram.notifyFinish("❌ FAILURE", env.BUILD_USER, currentBuild.duration)
                }
            }
        }
        always {
                sh 'docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"'
        }
    }
}

